In [1]:
import pandas as pd

In [3]:
countries = pd.read_csv("../data-version2/raw/cities/country-quality-of-indexes.csv")
countries.head()

,country,Purchasing Power Index,Purchasing Power Index Category,Safety Index,Safety Index Category,Health Care Index,Health Care Index Category,Climate Index,Climate Index Category,Cost of Living Index,Cost of Living Index Category,Property Price to Income Ratio,Property Price to Income Ratio Category,Traffic Commute Time Index,Traffic Commute Time Index Category,Pollution Index,Pollution Index Category,Quality of Life Index,Quality of Life Index Category
0,Afghanistan,22.41,Very Low,22.71,Low,26.98,Low,?,NaN,22.17,Very Low,14.03,High,56.17,Very High,86.83,Very High,?,NaN
1,Aland Islands,99.96,High,77.81,High,87.27,Very High,?,NaN,73.13,High,4.36,Very Low,19.05,Very Low,15.00,Very Low,?,NaN
2,Albania,24.62,Very Low,54.30,Moderate,50.54,Moderate,86.43,Very High,35.81,Very Low,17.11,Very High,38.21,Moderate,78.78,High,93.71,Very Low
3,Alderney,?,NaN,91.67,Very High,100.00,Very High,?,NaN,?,NaN,?,NaN,?,NaN,3.45,Very Low,?,NaN
4,Algeria,24.80,Very Low,45.92,Moderate,52.74,Moderate,94.82,Very High,26.85,Very Low,17.71,Very High,48.89,High,65.00,High,97.42,Very Low

In [7]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 19 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  234 non-null    object
 1   Purchasing Power Index                   234 non-null    object
 2   Purchasing Power Index Category          181 non-null    object
 3   Safety Index                             234 non-null    object
 4   Safety Index Category                    232 non-null    object
 5   Health Care Index                        234 non-null    object
 6   Health Care Index Category               212 non-null    object
 7   Climate Index                            234 non-null    object
 8   Climate Index Category                   125 non-null    object
 9   Cost of Living Index                     234 non-null    object
 10  Cost of Living Index Category            181 non-null    object
 11  Property Price to Income Ratio           234 non-null    object
 12  Property Price to Income Ratio Category  196 non-null    object
 13  Traffic Commute Time Index               234 non-null    object
 14  Traffic Commute Time Index Category      200 non-null    object
 15  Pollution Index                          234 non-null    object
 16  Pollution Index Category                 215 non-null    object
 17  Quality of Life Index                    234 non-null    object
 18  Quality of Life Index Category           125 non-null    object
dtypes: object(19)
memory usage: 34.9+ KB

In [5]:
cities = pd.read_csv("../data-version2/raw/cities/city-quality-of-indexes.csv")
cities.head()

,city,country,Purchasing Power Index,Purchasing Power Index Category,Safety Index,Safety Index Category,Health Care Index,Health Care Index Category,Climate Index,Climate Index Category,Cost of Living Index,Cost of Living Index Category,Property Price to Income Ratio,Property Price to Income Ratio Category,Traffic Commute Time Index,Traffic Commute Time Index Category,Pollution Index,Pollution Index Category,Quality of Life Index,Quality of Life Index Category
0,Constantine,Algeria,24.92,Very Low,55.32,Moderate,40.28,Moderate,84.71,Very High,27.61,Very Low,14.00,High,55.5,Very High,68.82,High,91.58,Very Low
1,Jijel,Algeria,?,NaN,54.66,Moderate,43.06,Moderate,?,NaN,?,NaN,13.02,High,20.0,Very Low,53.45,Moderate,?,NaN
2,Oran,Algeria,21.01,Very Low,45.78,Moderate,55.32,Moderate,96.35,Very High,28.43,Very Low,22.22,Very High,105.0,Very High,58.87,Moderate,68.73,Very Low
3,Setif,Algeria,20.84,Very Low,39.92,Low,59.26,Moderate,80.17,Very High,26.38,Very Low,94.89,Very High,13.5,Very Low,72.41,High,26.16,Very Low
4,Skikda,Algeria,?,NaN,86.76,Very High,22.22,Low,?,NaN,?,NaN,?,NaN,3.0,Very Low,117.24,Very High,?,NaN

In [8]:
cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283 entries, 0 to 282
Data columns (total 20 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   city                                     283 non-null    object
 1   country                                  283 non-null    object
 2   Purchasing Power Index                   283 non-null    object
 3   Purchasing Power Index Category          100 non-null    object
 4   Safety Index                             283 non-null    float64
 5   Safety Index Category                    283 non-null    object
 6   Health Care Index                        283 non-null    float64
 7   Health Care Index Category               283 non-null    object
 8   Climate Index                            283 non-null    object
 9   Climate Index Category                   211 non-null    object
 10  Cost of Living Index                     283 non-null    object
 11  Cost of Living Index Category            100 non-null    object
 12  Property Price to Income Ratio           283 non-null    object
 13  Property Price to Income Ratio Category  216 non-null    object
 14  Traffic Commute Time Index               283 non-null    float64
 15  Traffic Commute Time Index Category      283 non-null    object
 16  Pollution Index                          283 non-null    float64
 17  Pollution Index Category                 283 non-null    object
 18  Quality of Life Index                    283 non-null    object
 19  Quality of Life Index Category           79 non-null     object
dtypes: float64(4), object(16)
memory usage: 44.3+ KB

In [10]:
cities[cities["country"] == "Canada"]

,city,country,Purchasing Power Index,Purchasing Power Index Category,Safety Index,Safety Index Category,Health Care Index,Health Care Index Category,Climate Index,Climate Index Category,Cost of Living Index,Cost of Living Index Category,Property Price to Income Ratio,Property Price to Income Ratio Category,Traffic Commute Time Index,Traffic Commute Time Index Category,Pollution Index,Pollution Index Category,Quality of Life Index,Quality of Life Index Category
42,Airdrie,Canada,?,NaN,62.06,High,87.50,Very High,?,NaN,?,NaN,5.17,Low,31.00,Low,43.97,Moderate,?,NaN
43,Kanata,Canada,?,NaN,24.37,Low,69.44,High,45.15,Moderate,?,NaN,6.24,Low,7.00,Very Low,3.45,Very Low,?,NaN
44,Maple Ridge,Canada,85.53,High,49.30,Moderate,75.56,High,34.74,Moderate,73.26,High,6.42,Low,37.00,Moderate,41.38,Moderate,140.83,Moderate
45,Milton,Canada,?,NaN,58.53,Moderate,90.74,Very High,53.31,Moderate,?,NaN,4.23,Very Low,30.00,Low,26.01,Low,?,NaN
46,Nelson BC,Canada,?,NaN,66.76,High,80.56,Very High,71.69,High,?,NaN,6.60,Low,26.67,Very Low,12.84,Very Low,?,NaN
47,North Vancouver,Canada,119.43,Very High,79.47,High,75.23,High,91.15,Very High,68.34,Moderate,8.91,Moderate,49.62,High,16.94,Very Low,196.13,Very High
48,Okotoks,Canada,?,NaN,83.82,Very High,88.89,Very High,?,NaN,?,NaN,?,NaN,30.00,Low,10.34,Very Low,?,NaN
49,Prince Albert,Canada,?,NaN,37.35,Low,83.33,Very High,9.08,Low,?,NaN,?,NaN,15.00,Very Low,33.62,Low,?,NaN
50,Woodstock,Canada,?,NaN,44.33,Moderate,66.67,High,55.89,Moderate,?,NaN,5.07,Low,8.00,Very Low,53.45,Moderate,?,NaN